from pynput.mouse import Button, Controller as mo
from pynput.keyboard import Key, Controller as ke
import time
import os

x=0
mouse = mo()
keyb = ke()

while x <= 10:

    mouse.position = (8,250)
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position = (678,445)
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position = (678,445)
    time.sleep(4)
    mouse.click(Button.right)
    time.sleep(4)
    mouse.position = (744,536)
    mouse.click(Button.left)
    time.sleep(3)
    keyb.press('5')
    keyb.release('5')
    time.sleep(3)
    mouse.position = (1265,36)
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position=(1284,457)
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position = (678,445)
    mouse.click(Button.right)
    time.sleep(3)
    mouse.position = (744,536)
    mouse.click(Button.left)
    time.sleep(3)
    keyb.press('4')
    keyb.release('4')
    time.sleep(3)
    mouse.position = (1265,36)
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position=(1284,457)
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position = (678,445)
    mouse.click(Button.right)
    time.sleep(3)
    mouse.position = (744,536)
    mouse.click(Button.left)
    time.sleep(3)
    keyb.press('3')
    keyb.release('3')
    time.sleep(3)
    mouse.position = (1265,36)
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position=(1284,457)
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position = (678,445)
    mouse.click(Button.right)
    time.sleep(3)
    mouse.position = (744,536)
    mouse.click(Button.left)
    time.sleep(3)
    keyb.press('2')
    keyb.release('2')
    time.sleep(3)
    mouse.position = (1265,36)
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position=(1284,457)
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position = (678,445)
    mouse.click(Button.right)
    time.sleep(3)
    mouse.position = (744,536)
    mouse.click(Button.left)
    time.sleep(3)
    keyb.press('1')
    keyb.release('1')
    time.sleep(3)
    mouse.position = (1265,36)
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (1281,202)
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (924,405)
    mouse.click(Button.left,3)
    time.sleep(3)
    with keyb.pressed(Key.ctrl):
        keyb.press('c')
        keyb.press('c')
    time.sleep(3)
    mouse.position= (2713,680) #abrir programa de conversão das imagens
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (1386,71)
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (1446,100)
    mouse.click(Button.left)
    time.sleep(3)
    with keyb.pressed(Key.ctrl):
        keyb.press('a')
        keyb.press('a')
    time.sleep(3)
    mouse.position= (2616,49) #colocar na posição open
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (2128,105) #selecionar todos
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (1675,108) #converte
    mouse.click(Button.left)
    time.sleep(5)
    mouse.position= (2283,526) #close
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (2687,59) #abrir chrome
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (1964,131)
    mouse.click(Button.left)
    time.sleep(4)
    mouse.position= (1882,308)
    mouse.click(Button.left)
    time.sleep(4)
    with keyb.pressed(Key.ctrl):
        keyb.press('a')
        keyb.press('a')
    time.sleep(3)
    keyb.press(Key.enter)
    keyb.release(Key.enter)
    time.sleep(10)
    mouse.position= (1871,412)
    mouse.click(Button.left)
    time.sleep(10)
    with keyb.pressed(Key.ctrl):
        keyb.press('v')
        keyb.release('v')
    time.sleep(3)
    keyb.press(Key.f11) #tela cheia
    keyb.release(Key.f11)
    time.sleep(3)
    mouse.position= (1948,231)
    mouse.click(Button.left)
    time.sleep(3)
    keyb.type('Matrizes para Bordados')
    time.sleep(3)
    mouse.position= (1948,295)
    mouse.click(Button.left)
    time.sleep(3)
    keyb.type('999')
    time.sleep(3)
    mouse.position= (1954,314)
    mouse.click(Button.left)
    time.sleep(3)
    keyb.type('19,90')
    time.sleep(3)
    os.system("rm -r teste01/")
    time.sleep(3)
    os.system("mkdir teste01/")
    time.sleep(3)
    os.system("rm -r pynput/")
    time.sleep(3)
    os.system("mkdir pynput/")
    time.sleep(3)
    mouse.position= (1951,272)
    mouse.click(Button.left)
    time.sleep(3)
    keyb.type('matriz, matriz de bordado, matrizes de bordado, bordado computadorizado,')
    time.sleep(3)
    keyb.press(Key.f11) #tirar tela cheia
    keyb.release(Key.f11)
    time.sleep(6)
    mouse.position= (2691,389)
    mouse.click(Button.left)
    time.sleep(3)
    with keyb.pressed(Key.ctrl):
        keyb.press('a')
        keyb.release('a')
    time.sleep(3)
    with keyb.pressed(Key.ctrl):
        keyb.press('c')
        keyb.release('c')
    time.sleep(3)
    mouse.position= (2692,55)
    mouse.click(Button.left)
    time.sleep(3)
    keyb.press(Key.f11) #tirar tela cheia
    keyb.release(Key.f11)
    time.sleep(6)
    mouse.position= (1956,394)
    mouse.click(Button.left)
    time.sleep(3)
    with keyb.pressed(Key.ctrl):
        keyb.press('v')
        keyb.release('v')
    time.sleep(3)
    mouse.position= (2063,428) # clique no tipo
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (1972,454) # clique no tipo
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (2062,440) # clique no tipo
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (1953,490) # clique no tipo
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (2061,452) # clique no tipo
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (1978,518) # clique no tipo
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (1660,559) # clicar no branco
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (1890,659) #clicar em não aplica cálculo
    mouse.click(Button.left)
    time.sleep(3)
    mouse.position= (2018,725)#salvar
    mouse.click(Button.left)
    time.sleep(3)
    keyb.press(Key.f11) #tirar tela cheia
    keyb.release(Key.f11)
    time.sleep(6)
    mouse.position= (14,51)
    mouse.click(Button.left)
    time.sleep(3)
    with keyb.pressed(Key.ctrl):
        keyb.press('w')
        keyb.release('w')
        time.sleep(10)

    x+=1
    

    

